# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2023.01.10-h06a4308_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-cudart-11.7.99-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-cupti-11.7.101-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvrtc-11.7.99-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvtx-11.7.91-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2021.4.0-h06a4308_3561.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://conda.anaconda.org/nvidia/linux-64/libcublas-11.10.3.66-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufft-10.7.2.124-h4fbf590_0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufile-1.6.1.9-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcurand-10.3.2.106-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusolver-11.4.0.1-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusparse-11.7.4.91-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran5-11.2.0-h1234567_1.conda
https://conda.anaconda.org/nvidia/linux-64/libnpp-11.7.4.75-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnvjpeg-11.8.0.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-libraries-11.7.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-11.2.0-h00389a5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2021.4.0-h06a4308_640.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-runtime-11.7.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-cuda-11.7-h778d358_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/abseil-cpp-20211102.0-hd4dd3e8_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/charls-2.2.0-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.4.9-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.2.1-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.2.1-h295c915_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jxrlib-1.1-h7b6447c_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/lame-3.100-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libaec-1.0.4-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlicommon-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.17-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libev-4.33-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.2-h6a678d5_6.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h7f8727e_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtasn1-4.19.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libunistring-0.9.10-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.2.4-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.15-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libzopfli-1.0.3-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nspr-4.33-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openh264-2.1.1-h4ff587b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1t-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.45-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/re2-2022.04.01-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/snappy-1.1.9-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zfp-0.5.5-h295c915_6.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.69.1-he621ea3_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlidec-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlienc-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20221030-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libevent-2.1.12-h8f2d780_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libidn2-2.3.2-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libllvm14-14.0.6-hdb19cb5_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnghttp2-1.46.0-hce63b2e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-3.20.3-he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.10.0-h8f2d780_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.10.3-hcbfbd50_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpfr-4.0.2-hb69a4c5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nettle-3.7.3-hbbd107a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.5-hc292b87_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blosc-1.21.3-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-bin-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gnutls-3.6.15-he1e5248_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/grpc-cpp-1.48.2-h5bf31a4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.1-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.19.4-h568e23c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libclang13-14.0.6-default_he11475f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.0-h6a678d5_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxkbcommon-1.0.1-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxslt-1.1.37-h2085143_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpc-1.1.0-h10f8cd9_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.41.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-h5eee18b_7.conda
https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.14.1-h4c34cd2_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.1-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libclang-14.0.6-default_hc6dbbc7_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-7.88.1-h91b91d3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-12.9-h16c4e8d_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.2.4-h11a3e52_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nss-3.74-h0370c37_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openjpeg-2.4.0-h3ad879b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.10.11-h7a1cb2a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/absl-py-1.3.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/appdirs-1.4.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/async-timeout-4.0.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-22.1.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blinker-1.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brunsli-0.1-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cachetools-4.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2022.12.7-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cfitsio-3.470-h5893167_7.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.0.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cloudpickle-2.2.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/filelock-3.9.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/frozenlist-1.3.3-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fsspec-2023.4.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmpy2-2.1.2-py310heeb90bb_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.4-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lazy_loader-0.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/locket-1.0.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markdown-3.4.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.1-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpmath-1.2.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/multidict-6.0.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-2.8.4-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-23.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-9.4.0-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ply-3.11-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/protobuf-3.20.3-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyasn1-0.4.8-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyjwt-2.4.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-3.0.9-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-6.0-py310h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-main-5.15.2-h8373d8f_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-66.0.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorboard-data-server-0.7.0-py310h52d8a92_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/toolz-0.12.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tqdm-4.65.0-py310h2f386ee_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.5.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.38.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.11.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/aiosignal-1.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py310h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.12.0-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/grpcio-1.48.2-py310h5bf31a4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-6.0.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/noarch/partd-1.2.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-23.0.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyasn1-modules-0.2.8-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-webengine-5.15.9-hbbf29b9_6.conda
https://repo.anaconda.com/pkgs/main/noarch/rsa-4.7.2-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-6.6.2-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sympy-1.11.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorboard-plugin-wit-1.8.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/werkzeug-2.2.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yarl-1.8.1-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/aiohttp-3.8.3-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py310h7f8727e_1002.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-39.0.1-py310h9ce1e76_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dask-core-2023.4.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.24.3-py310h8e6c178_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt5-sip-12.11.0-py310h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtwebkit-5.212-h3fafdc1_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/oauthlib-3.2.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.0.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.15.7-py310h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.15-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.29.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/google-auth-2.6.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pooch-1.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/requests-oauthlib-1.3.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/google-auth-oauthlib-0.5.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/contourpy-1.0.5-py310hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/imagecodecs-2021.8.26-py310h46e8fbd_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/imageio-2.26.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.7.1-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.7.1-py310h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.1-py310hd6ae3a3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py310h00e6091_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.24.3-py310hd5efca6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pywavelets-1.4.1-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.10.1-py310hd5efca6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorboard-2.12.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tifffile-2021.7.2-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-image-0.20.0-py310h6a678d5_0.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-2.0.0-py3.10_cuda11.7_cudnn8.5.0_0.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchaudio-2.0.0-py310_cu117.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchtriton-2.0.0-py310.tar.bz2
https://conda.anaconda.org/pytorch/linux-64/torchvision-0.15.0-py310_cu117.tar.bz2
